"""unit scoped quizzes

Lets one quiz span a whole unit instead of a single sub-unit, so a cumulative
test can interleave questions from every sub-unit on the paper.

  * ``quizzes.sub_unit_id`` becomes nullable, and ``quizzes.unit_id`` is added.
    Exactly one of the two is set, enforced by a check constraint rather than
    by convention -- a unit test that also named a sub-unit would silently move
    that sub-unit's progress.
  * ``quizzes.is_unit_test`` marks a cumulative paper.
  * ``quiz_questions.sub_unit_id`` records which sub-unit each question
    teaches. Redundant for an ordinary quiz and the only source of truth for a
    unit test, where consecutive questions come from different sub-units by
    design. Backfilled from the parent quiz so existing per-skill analysis
    keeps working.
  * ``quiz_attempts`` follows the same scoping, so history rows stay joinable.

Hand-written rather than autogenerated. Against this project's SQLite database
autogenerate reliably emits two things batch mode cannot execute: unnamed
foreign keys (batch rebuilds the table and needs every constraint named), and
``nullable=False`` with no server default (fine against an empty table, fatal
against one with rows).

Revision ID: a1f4c07b93de
Revises: eedfb671041a
Create Date: 2026-09-09 16:41:12.004518
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a1f4c07b93de"
down_revision: str | None = "eedfb671041a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Batch mode recreates each table, so every constraint it carries needs a name.
NAMING_CONVENTION = {
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "pk": "pk_%(table_name)s",
}

SCOPE_CHECK = "ck_quizzes_quiz_scope_exactly_one"


def upgrade() -> None:
    """Widen quizzes, quiz_questions and quiz_attempts to unit scope."""
    # ----------------------------------------------------------------- #
    # quiz_questions: attribute every question to its own sub-unit
    # ----------------------------------------------------------------- #
    with op.batch_alter_table(
        "quiz_questions", schema=None, naming_convention=NAMING_CONVENTION
    ) as batch_op:
        batch_op.add_column(sa.Column("sub_unit_id", sa.String(length=36), nullable=True))
        batch_op.create_index("ix_quiz_questions_sub_unit_id", ["sub_unit_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_quiz_questions_sub_unit_id_curriculum_sub_units",
            "curriculum_sub_units",
            ["sub_unit_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # Existing questions all belong to a single-sub-unit quiz, so the parent
    # already holds the right answer. Doing this before quizzes.sub_unit_id
    # becomes nullable means every row here gets a value.
    op.execute(
        """
        UPDATE quiz_questions
           SET sub_unit_id = (
               SELECT quizzes.sub_unit_id
                 FROM quizzes
                WHERE quizzes.id = quiz_questions.quiz_id
           )
         WHERE sub_unit_id IS NULL
        """
    )

    # ----------------------------------------------------------------- #
    # quizzes: either a sub-unit or a unit, never both
    # ----------------------------------------------------------------- #
    with op.batch_alter_table(
        "quizzes", schema=None, naming_convention=NAMING_CONVENTION
    ) as batch_op:
        batch_op.alter_column(
            "sub_unit_id", existing_type=sa.String(length=36), nullable=True
        )
        batch_op.add_column(sa.Column("unit_id", sa.String(length=36), nullable=True))
        batch_op.add_column(
            sa.Column(
                "is_unit_test",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.create_index("ix_quizzes_unit_id", ["unit_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_quizzes_unit_id_curriculum_units",
            "curriculum_units",
            ["unit_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_check_constraint(
            SCOPE_CHECK,
            "(sub_unit_id IS NOT NULL AND unit_id IS NULL) "
            "OR (sub_unit_id IS NULL AND unit_id IS NOT NULL)",
        )

    # ----------------------------------------------------------------- #
    # quiz_attempts: history follows the same scoping
    # ----------------------------------------------------------------- #
    with op.batch_alter_table(
        "quiz_attempts", schema=None, naming_convention=NAMING_CONVENTION
    ) as batch_op:
        batch_op.alter_column(
            "sub_unit_id", existing_type=sa.String(length=36), nullable=True
        )
        batch_op.add_column(sa.Column("unit_id", sa.String(length=36), nullable=True))
        batch_op.add_column(
            sa.Column(
                "is_unit_test",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.create_index("ix_quiz_attempts_unit_id", ["unit_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_quiz_attempts_unit_id_curriculum_units",
            "curriculum_units",
            ["unit_id"],
            ["id"],
            ondelete="CASCADE",
        )


def downgrade() -> None:
    """Narrow back to sub-unit scope, discarding any unit tests.

    Unit tests cannot be represented once ``sub_unit_id`` is NOT NULL again, so
    they are deleted rather than silently re-pointed at an arbitrary sub-unit.
    That is destructive, and deliberately so: guessing a scope would corrupt
    progress in a way nothing downstream could detect.

    These batches deliberately omit ``NAMING_CONVENTION``. Batch mode reflects
    the table before rebuilding it, and the convention would re-prefix the
    names SQLite already holds -- so a drop would go looking for
    ``ck_quizzes_ck_quizzes_...`` and find nothing.
    """
    op.execute("DELETE FROM quiz_attempts WHERE unit_id IS NOT NULL")
    op.execute("DELETE FROM quizzes WHERE unit_id IS NOT NULL")

    with op.batch_alter_table("quiz_attempts", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_quiz_attempts_unit_id_curriculum_units", type_="foreignkey"
        )
        batch_op.drop_index("ix_quiz_attempts_unit_id")
        batch_op.drop_column("is_unit_test")
        batch_op.drop_column("unit_id")
        batch_op.alter_column(
            "sub_unit_id", existing_type=sa.String(length=36), nullable=False
        )

    with op.batch_alter_table("quizzes", schema=None) as batch_op:
        batch_op.drop_constraint(SCOPE_CHECK, type_="check")
        batch_op.drop_constraint("fk_quizzes_unit_id_curriculum_units", type_="foreignkey")
        batch_op.drop_index("ix_quizzes_unit_id")
        batch_op.drop_column("is_unit_test")
        batch_op.drop_column("unit_id")
        batch_op.alter_column(
            "sub_unit_id", existing_type=sa.String(length=36), nullable=False
        )

    with op.batch_alter_table("quiz_questions", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_quiz_questions_sub_unit_id_curriculum_sub_units", type_="foreignkey"
        )
        batch_op.drop_index("ix_quiz_questions_sub_unit_id")
        batch_op.drop_column("sub_unit_id")
