"""curriculum uploads

Adds ``curriculum_uploads``: one row per attempt at ingesting a curriculum PDF.

Ingestion takes minutes, so it cannot run inside the upload request. This table
is what the parent polls while it runs. It is a real table rather than
in-memory job state because a restart mid-ingest would otherwise leave them
watching a spinner with nothing behind it, and because "what did I upload, and
did it work?" should still be answerable tomorrow.

Hand-written rather than autogenerated, like the migrations before it: against
SQLite, autogenerate emits unnamed foreign keys that batch mode cannot execute.

Revision ID: b882273cd4c1
Revises: d5c81a2f60b7
Create Date: 2026-09-09 18:31:07.921544
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b882273cd4c1"
down_revision: str | None = "d5c81a2f60b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the upload record table."""
    op.create_table(
        "curriculum_uploads",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("stored_path", sa.String(length=500), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("subject", sa.String(length=80), nullable=False, server_default="math"),
        sa.Column("grade_level", sa.Integer(), nullable=True),
        # The enum stores its value ("pending"), matching every other enum here,
        # so the raw SQLite file stays readable.
        sa.Column("status", sa.String(length=20), nullable=False, server_default="pending"),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("units_written", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("sub_units_written", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("chunks_created", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("vectors_upserted", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("warnings", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_curriculum_uploads_user_id_users",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_curriculum_uploads"),
    )
    op.create_index("ix_curriculum_uploads_user_id", "curriculum_uploads", ["user_id"])
    op.create_index("ix_curriculum_uploads_status", "curriculum_uploads", ["status"])
    op.create_index("ix_curriculum_uploads_content_hash", "curriculum_uploads", ["content_hash"])
    op.create_index("ix_upload_user_status", "curriculum_uploads", ["user_id", "status"])


def downgrade() -> None:
    """Drop the upload records.

    The curricula they produced are untouched -- those live in
    ``curriculum_units`` and belong to the parent regardless of whether the
    record of how they arrived still exists.
    """
    op.drop_index("ix_upload_user_status", table_name="curriculum_uploads")
    op.drop_index("ix_curriculum_uploads_content_hash", table_name="curriculum_uploads")
    op.drop_index("ix_curriculum_uploads_status", table_name="curriculum_uploads")
    op.drop_index("ix_curriculum_uploads_user_id", table_name="curriculum_uploads")
    op.drop_table("curriculum_uploads")
