"""initial schema with question bank

Revision ID: c2b66ef7c503
Revises: 
Create Date: 2026-09-09 10:47:30.351205

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2b66ef7c503"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "curriculum_units",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("unit_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("subject", sa.String(length=80), nullable=False),
        sa.Column("grade_level", sa.Integer(), nullable=False),
        sa.Column("source_document", sa.String(length=255), nullable=True),
        sa.Column("source_page_start", sa.Integer(), nullable=True),
        sa.Column("source_page_end", sa.Integer(), nullable=True),
        sa.Column("total_sub_units", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subject", "grade_level", "unit_number", name="uq_unit_identity"),
    )
    with op.batch_alter_table("curriculum_units", schema=None) as batch_op:
        batch_op.create_index("ix_unit_subject_grade", ["subject", "grade_level"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=150), nullable=False),
        sa.Column(
            "role",
            sa.Enum("parent", "teacher", "admin", name="userrole", native_enum=False),
            nullable=False,
        ),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("email_opt_in", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_role"), ["role"], unique=False)

    op.create_table(
        "curriculum_sub_units",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("unit_id", sa.String(length=36), nullable=False),
        sa.Column("sub_unit_number", sa.String(length=20), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("learning_objectives", sa.JSON(), nullable=True),
        sa.Column("skill_tags", sa.JSON(), nullable=True),
        sa.Column("source_page_start", sa.Integer(), nullable=True),
        sa.Column("source_page_end", sa.Integer(), nullable=True),
        sa.Column("vector_namespace", sa.String(length=120), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("is_indexed", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["unit_id"], ["curriculum_units.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("unit_id", "sub_unit_number", name="uq_sub_unit_identity"),
    )
    with op.batch_alter_table("curriculum_sub_units", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_curriculum_sub_units_unit_id"), ["unit_id"], unique=False
        )
        batch_op.create_index("ix_sub_unit_unit_sequence", ["unit_id", "sequence"], unique=False)

    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=255), nullable=False),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index("ix_session_user_active", ["user_id", "revoked_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_sessions_refresh_token_hash"), ["refresh_token_hash"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "students",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("first_name", sa.String(length=80), nullable=False),
        sa.Column("last_name", sa.String(length=80), nullable=True),
        sa.Column("grade_level", sa.Integer(), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("school_name", sa.String(length=150), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("students", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_students_grade_level"), ["grade_level"], unique=False)
        batch_op.create_index(batch_op.f("ix_students_user_id"), ["user_id"], unique=False)

    op.create_table(
        "achievement_badges",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("badge_key", sa.String(length=80), nullable=False),
        sa.Column("badge_name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=80), nullable=True),
        sa.Column("tier", sa.String(length=20), nullable=False),
        sa.Column("points_awarded", sa.Integer(), nullable=False),
        sa.Column("context", sa.JSON(), nullable=True),
        sa.Column("unlocked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("student_id", "badge_key", name="uq_badge_per_student"),
    )
    with op.batch_alter_table("achievement_badges", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_achievement_badges_student_id"), ["student_id"], unique=False
        )

    op.create_table(
        "gamification_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("total_points", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("points_to_next_level", sa.Integer(), nullable=False),
        sa.Column("current_streak_days", sa.Integer(), nullable=False),
        sa.Column("longest_streak_days", sa.Integer(), nullable=False),
        sa.Column("last_activity_date", sa.Date(), nullable=True),
        sa.Column("avatar_key", sa.String(length=60), nullable=False),
        sa.Column("unlocked_avatars", sa.JSON(), nullable=True),
        sa.Column("total_quizzes_completed", sa.Integer(), nullable=False),
        sa.Column("total_correct_answers", sa.Integer(), nullable=False),
        sa.Column("total_sub_units_completed", sa.Integer(), nullable=False),
        sa.Column("total_units_completed", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("gamification_profiles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_gamification_profiles_student_id"), ["student_id"], unique=True
        )

    op.create_table(
        "notifications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "daily_reminder",
                "weekly_report",
                "achievement_unlock",
                "unit_complete",
                name="notificationtype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "channel",
            sa.Enum("email", "in_app", name="notificationchannel", native_enum=False),
            nullable=False,
        ),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("is_sent", sa.Boolean(), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("send_attempts", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index("ix_notification_pending", ["is_sent", "scheduled_for"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_notifications_student_id"), ["student_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_notifications_type"), ["type"], unique=False)
        batch_op.create_index(batch_op.f("ix_notifications_user_id"), ["user_id"], unique=False)

    op.create_table(
        "question_bank",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("sub_unit_id", sa.String(length=36), nullable=False),
        sa.Column(
            "difficulty_level",
            sa.Enum(
                "beginner", "intermediate", "proficient", name="difficultylevel", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column(
            "question_type",
            sa.Enum(
                "multiple_choice",
                "true_false",
                "numeric",
                "short_answer",
                name="questiontype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("options", sa.JSON(), nullable=True),
        sa.Column("correct_answer", sa.String(length=500), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("distractor_rationales", sa.JSON(), nullable=True),
        sa.Column("hint", sa.Text(), nullable=True),
        sa.Column("skill_tag", sa.String(length=120), nullable=True),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("source_chunk_ids", sa.JSON(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("generation_metadata", sa.JSON(), nullable=True),
        sa.Column("verification_status", sa.String(length=20), nullable=False),
        sa.Column("verifier_answer", sa.String(length=10), nullable=True),
        sa.Column("verification_votes", sa.JSON(), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("times_served", sa.Integer(), nullable=False),
        sa.Column("last_served_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["sub_unit_id"], ["curriculum_sub_units.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "sub_unit_id", "difficulty_level", "content_hash", name="uq_bank_question_content"
        ),
    )
    with op.batch_alter_table("question_bank", schema=None) as batch_op:
        batch_op.create_index(
            "ix_bank_slot", ["sub_unit_id", "difficulty_level", "is_active"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_question_bank_content_hash"), ["content_hash"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_question_bank_skill_tag"), ["skill_tag"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_question_bank_sub_unit_id"), ["sub_unit_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_question_bank_verification_status"),
            ["verification_status"],
            unique=False,
        )

    op.create_table(
        "quizzes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("sub_unit_id", sa.String(length=36), nullable=False),
        sa.Column(
            "difficulty_level",
            sa.Enum(
                "beginner", "intermediate", "proficient", name="difficultylevel", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "in_progress",
                "completed",
                "abandoned",
                name="quizstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("total_questions", sa.Integer(), nullable=False),
        sa.Column("correct_count", sa.Integer(), nullable=False),
        sa.Column("score_percentage", sa.Float(), nullable=True),
        sa.Column("passing_threshold", sa.Float(), nullable=False),
        sa.Column("is_passed", sa.Boolean(), nullable=False),
        sa.Column("is_practice", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_spent_seconds", sa.Integer(), nullable=False),
        sa.Column("generation_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "score_percentage IS NULL OR (score_percentage >= 0 AND score_percentage <= 100)",
            name="ck_quiz_score_range",
        ),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sub_unit_id"], ["curriculum_sub_units.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("quizzes", schema=None) as batch_op:
        batch_op.create_index(
            "ix_quiz_student_subunit",
            ["student_id", "sub_unit_id", "difficulty_level"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_quizzes_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_quizzes_student_id"), ["student_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_quizzes_sub_unit_id"), ["sub_unit_id"], unique=False)

    op.create_table(
        "sub_unit_progress",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("sub_unit_id", sa.String(length=36), nullable=False),
        sa.Column("completion_percentage", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "not_started", "in_progress", "completed", name="progressstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("beginner_completed", sa.Boolean(), nullable=False),
        sa.Column("intermediate_completed", sa.Boolean(), nullable=False),
        sa.Column("proficient_completed", sa.Boolean(), nullable=False),
        sa.Column("beginner_best_score", sa.Float(), nullable=False),
        sa.Column("intermediate_best_score", sa.Float(), nullable=False),
        sa.Column("proficient_best_score", sa.Float(), nullable=False),
        sa.Column("total_attempts", sa.Integer(), nullable=False),
        sa.Column("total_time_seconds", sa.Integer(), nullable=False),
        sa.Column("celebration_shown", sa.Boolean(), nullable=False),
        sa.Column("first_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "completion_percentage IN (0, 33, 67, 100)", name="ck_progress_percentage_steps"
        ),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sub_unit_id"], ["curriculum_sub_units.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("student_id", "sub_unit_id", name="uq_progress_identity"),
    )
    with op.batch_alter_table("sub_unit_progress", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sub_unit_progress_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_sub_unit_progress_student_id"), ["student_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sub_unit_progress_sub_unit_id"), ["sub_unit_id"], unique=False
        )

    op.create_table(
        "quiz_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("sub_unit_id", sa.String(length=36), nullable=False),
        sa.Column("quiz_id", sa.String(length=36), nullable=False),
        sa.Column(
            "difficulty_level",
            sa.Enum(
                "beginner", "intermediate", "proficient", name="difficultylevel", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("total_questions", sa.Integer(), nullable=False),
        sa.Column("correct_count", sa.Integer(), nullable=False),
        sa.Column("score_percentage", sa.Float(), nullable=False),
        sa.Column("is_passed", sa.Boolean(), nullable=False),
        sa.Column("is_practice", sa.Boolean(), nullable=False),
        sa.Column("skill_breakdown", sa.JSON(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["quiz_id"], ["quizzes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sub_unit_id"], ["curriculum_sub_units.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("quiz_id"),
    )
    with op.batch_alter_table("quiz_attempts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_attempt_student_subunit",
            ["student_id", "sub_unit_id", "difficulty_level"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_quiz_attempts_student_id"), ["student_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_quiz_attempts_sub_unit_id"), ["sub_unit_id"], unique=False
        )

    op.create_table(
        "quiz_questions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("quiz_id", sa.String(length=36), nullable=False),
        sa.Column("question_number", sa.Integer(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column(
            "question_type",
            sa.Enum(
                "multiple_choice",
                "true_false",
                "numeric",
                "short_answer",
                name="questiontype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("options", sa.JSON(), nullable=True),
        sa.Column("correct_answer", sa.String(length=500), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("distractor_rationales", sa.JSON(), nullable=True),
        sa.Column("hint", sa.Text(), nullable=True),
        sa.Column(
            "difficulty_level",
            sa.Enum(
                "beginner", "intermediate", "proficient", name="difficultylevel", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("skill_tag", sa.String(length=120), nullable=True),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("source_chunk_ids", sa.JSON(), nullable=True),
        sa.Column("bank_question_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["bank_question_id"], ["question_bank.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["quiz_id"], ["quizzes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("quiz_id", "question_number", name="uq_question_position"),
    )
    with op.batch_alter_table("quiz_questions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_quiz_questions_bank_question_id"), ["bank_question_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_quiz_questions_quiz_id"), ["quiz_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_quiz_questions_skill_tag"), ["skill_tag"], unique=False
        )

    op.create_table(
        "quiz_responses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("quiz_id", sa.String(length=36), nullable=False),
        sa.Column("question_id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("selected_answer", sa.String(length=500), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("hint_used", sa.Boolean(), nullable=False),
        sa.Column("feedback_shown", sa.Boolean(), nullable=False),
        sa.Column("time_spent_seconds", sa.Integer(), nullable=False),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["quiz_questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["quiz_id"], ["quizzes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("quiz_responses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_quiz_responses_question_id"), ["question_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_quiz_responses_quiz_id"), ["quiz_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_quiz_responses_student_id"), ["student_id"], unique=False
        )
        batch_op.create_index(
            "ix_response_student_question", ["student_id", "question_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("quiz_responses", schema=None) as batch_op:
        batch_op.drop_index("ix_response_student_question")
        batch_op.drop_index(batch_op.f("ix_quiz_responses_student_id"))
        batch_op.drop_index(batch_op.f("ix_quiz_responses_quiz_id"))
        batch_op.drop_index(batch_op.f("ix_quiz_responses_question_id"))

    op.drop_table("quiz_responses")
    with op.batch_alter_table("quiz_questions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quiz_questions_skill_tag"))
        batch_op.drop_index(batch_op.f("ix_quiz_questions_quiz_id"))
        batch_op.drop_index(batch_op.f("ix_quiz_questions_bank_question_id"))

    op.drop_table("quiz_questions")
    with op.batch_alter_table("quiz_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quiz_attempts_sub_unit_id"))
        batch_op.drop_index(batch_op.f("ix_quiz_attempts_student_id"))
        batch_op.drop_index("ix_attempt_student_subunit")

    op.drop_table("quiz_attempts")
    with op.batch_alter_table("sub_unit_progress", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sub_unit_progress_sub_unit_id"))
        batch_op.drop_index(batch_op.f("ix_sub_unit_progress_student_id"))
        batch_op.drop_index(batch_op.f("ix_sub_unit_progress_status"))

    op.drop_table("sub_unit_progress")
    with op.batch_alter_table("quizzes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quizzes_sub_unit_id"))
        batch_op.drop_index(batch_op.f("ix_quizzes_student_id"))
        batch_op.drop_index(batch_op.f("ix_quizzes_status"))
        batch_op.drop_index("ix_quiz_student_subunit")

    op.drop_table("quizzes")
    with op.batch_alter_table("question_bank", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_question_bank_verification_status"))
        batch_op.drop_index(batch_op.f("ix_question_bank_sub_unit_id"))
        batch_op.drop_index(batch_op.f("ix_question_bank_skill_tag"))
        batch_op.drop_index(batch_op.f("ix_question_bank_content_hash"))
        batch_op.drop_index("ix_bank_slot")

    op.drop_table("question_bank")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_user_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_type"))
        batch_op.drop_index(batch_op.f("ix_notifications_student_id"))
        batch_op.drop_index("ix_notification_pending")

    op.drop_table("notifications")
    with op.batch_alter_table("gamification_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_gamification_profiles_student_id"))

    op.drop_table("gamification_profiles")
    with op.batch_alter_table("achievement_badges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_achievement_badges_student_id"))

    op.drop_table("achievement_badges")
    with op.batch_alter_table("students", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_students_user_id"))
        batch_op.drop_index(batch_op.f("ix_students_grade_level"))

    op.drop_table("students")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_sessions_refresh_token_hash"))
        batch_op.drop_index("ix_session_user_active")

    op.drop_table("sessions")
    with op.batch_alter_table("curriculum_sub_units", schema=None) as batch_op:
        batch_op.drop_index("ix_sub_unit_unit_sequence")
        batch_op.drop_index(batch_op.f("ix_curriculum_sub_units_unit_id"))

    op.drop_table("curriculum_sub_units")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_role"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("curriculum_units", schema=None) as batch_op:
        batch_op.drop_index("ix_unit_subject_grade")

    op.drop_table("curriculum_units")
    # ### end Alembic commands ###
