"""hint requested on quiz questions

Adds ``quiz_questions.hint_requested`` so that "the student asked for a hint"
is recorded server-side rather than taken on trust from the client.

This migration also repairs schema drift. The development database was adopted
into Alembic with plain ``ALTER TABLE ADD COLUMN`` statements, which SQLite
cannot use to attach a foreign key -- so that database ended up without the
``bank_question_id`` foreign key and index that a fresh install gets from the
baseline migration. Adding them here converges the two.

Hand-edited from the autogenerated version, which could not run:
  * ``create_foreign_key(None, ...)`` -- SQLite batch mode rebuilds the table
    and cannot do that with an unnamed constraint.
  * ``add_column(..., nullable=False)`` with no server default -- fine against
    an empty table, fatal against one with rows.

Revision ID: eedfb671041a
Revises: c2b66ef7c503
Create Date: 2026-09-09 13:26:56.884287
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "eedfb671041a"
down_revision: str | None = "c2b66ef7c503"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Batch mode recreates the table, so every constraint it carries needs a name.
NAMING_CONVENTION = {
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "pk": "pk_%(table_name)s",
}

FK_NAME = "fk_quiz_questions_bank_question_id_question_bank"
IX_NAME = "ix_quiz_questions_bank_question_id"


def upgrade() -> None:
    """Add hint_requested, and backfill the bank_question_id FK and index."""
    connection = op.get_bind()
    inspector = sa.inspect(connection)

    existing_indexes = {index["name"] for index in inspector.get_indexes("quiz_questions")}
    existing_fks = {fk.get("name") for fk in inspector.get_foreign_keys("quiz_questions")}
    has_fk_to_bank = any(
        fk.get("referred_table") == "question_bank"
        for fk in inspector.get_foreign_keys("quiz_questions")
    )

    with op.batch_alter_table(
        "quiz_questions", schema=None, naming_convention=NAMING_CONVENTION
    ) as batch_op:
        # server_default so existing rows get a value; the ORM default takes
        # over for new rows.
        batch_op.add_column(
            sa.Column(
                "hint_requested",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        if IX_NAME not in existing_indexes:
            batch_op.create_index(IX_NAME, ["bank_question_id"], unique=False)
        if not has_fk_to_bank and FK_NAME not in existing_fks:
            batch_op.create_foreign_key(
                FK_NAME,
                "question_bank",
                ["bank_question_id"],
                ["id"],
                ondelete="SET NULL",
            )


def downgrade() -> None:
    """Remove hint_requested. The FK and index are left in place.

    They belong to the baseline schema and were only missing on databases
    adopted by hand; dropping them here would reintroduce the drift.
    """
    with op.batch_alter_table(
        "quiz_questions", schema=None, naming_convention=NAMING_CONVENTION
    ) as batch_op:
        batch_op.drop_column("hint_requested")
